apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tektoncd-tools-yq
  title: Tektoncd Tools - yq
  description: yq 是一个轻量级的 YAML/JSON/XML 命令行处理工具，在 Tekton 任务镜像（kubectl、kustomize、helm 等）中用于解析和修改配置文件。
  tags:
    - tool
    - yaml
    - open-source-fork
  links:
    - url: https://github.com/AlaudaDevops/yq
      title: GitHub Repository
      icon: github
    - url: https://build-sonar.alauda.cn/dashboard?id=github.com-AlaudaDevops-yq
      title: SonarQube
      icon: dashboard
    - url: https://github.com/mikefarah/yq
      title: Upstream Repository
      icon: github
  annotations:
    # github plugin
    github.com/project-slug: AlaudaDevops/yq
    # sonarqube plugin
    sonarqube.org/project-key: github.com-AlaudaDevops-yq
    # 开源组件代码仓库地址，格式：${url}/${project}/${repo}
    acp.cpaas.io/open-source-component-repo: https://github.com/mikefarah/yq
    # 开源组件的版本信息，只适用于开源组件，自研组件默认不收集版本信息,格式 ${version}
    acp.cpaas.io/open-source-component-version: v4.47.2
    # 开源组件的license信息,格式 ${license}
    acp.cpaas.io/open-source-component-license: MIT
    # 开源组件的license地址,格式 ${url}/${project}/${repo}/${license-path}
    acp.cpaas.io/open-source-component-license_url: https://github.com/mikefarah/yq/blob/master/LICENSE
    # backstage techdocs plugin
    backstage.io/techdocs-ref: dir:../
    acp.cpaas.io/owner: qingliu@alauda.io

    # 组件属性，区别是否部署时必带的核心组件,可选值为 core 和 plugin。
    acp.cpaas.io/functional-attributes: plugin

spec:
  type: service
  system: system:alauda-devops-system
  lifecycle: production
  owner: devops
