name: Release Alauda

on:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: alauda-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.1.0
          args: release -f=.goreleaser-alauda.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
